config/routes.rb
Xxi::Application.routes.draw do
  resources :games

  root :to => "games#index"

end

app/models/game.rb
class Game < ActiveRecord::Base
  GENRES = [:arcade, :action, :puzzle, :FPS, :strategy ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.xml
  def index
    genre = params[:genre]
    
    if genre.blank?
      @games = Game.all
    else
      @games = Game.where(:genre => genre)
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @games }
    end
  end

  # GET /games/1
  # GET /games/1.xml
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @game }
    end
  end

  # GET /games/new
  # GET /games/new.xml
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.xml
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to(@game, :notice => 'Game was successfully created.') }
        format.xml  { render :xml => @game, :status => :created, :location => @game }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.xml
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to(@game, :notice => 'Game was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.xml
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to(games_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game, :html => { :class => "form-stacked" }) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label :genre %>
    <%= f.select :genre, Game::GENRES%>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :provider %>
    <%= f.text_field :provider %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_sidebar.html.erb
  <% Game::GENRES.each do |genre| %>
    | <%= link_to genre.capitalize, games_path( :genre => genre) %>
  <% end %>|

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<%= render :partial => "sidebar" %>
<br />
<table class="common-table zebra-striped">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Genre</th>
    <th>Url</th>
    <th>Provider</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.name %></td>
    <td><%= game.description %></td>
    <td><%= game.genre %></td>
    <td><%= game.url %></td>
    <td><%= game.provider %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'New Game', new_game_path,:method => :get %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <b>Name:</b>
  <%= @game.name %>
</p>

<object id="FlashGame" wmode="opaque" codebase=
  "http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0"
  width="100%" height="100%">
  <param name="allowFullScreen" value="true" />
  <param name="movie" value="<%=@game.url%>" />
  <param name="wmode" value="opaque" />
  <param name="quality" value="high" />
  <embed wmode="opaque" src="<%=@game.url%>" allowfullscreen="true" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="100%" height="100%" class="FlashGame" id="FlashGame2" />
</object>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XXI</title>
  <%= stylesheet_link_tag "bootstrap-1.0.0" %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>